=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for KeycloakRest::IdentityProvidersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IdentityProvidersApi' do
  before do
    # run before each test
    @api_instance = KeycloakRest::IdentityProvidersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IdentityProvidersApi' do
    it 'should create an instance of IdentityProvidersApi' do
      expect(@api_instance).to be_instance_of(KeycloakRest::IdentityProvidersApi)
    end
  end

  # unit tests for realm_identity_provider_import_config_post
  # Import identity provider from uploaded JSON file
  # @param realm realm name (not id!)
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'realm_identity_provider_import_config_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_delete
  # Delete the identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_export_get
  # Export public broker configuration for identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :format Format to use
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_export_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_get
  # Get the identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param [Hash] opts the optional parameters
  # @return [IdentityProviderRepresentation]
  describe 'realm_identity_provider_instances_alias_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_management_permissions_get
  # Return object stating whether client Authorization permissions have been initialized or not and a reference
  # @param realm realm name (not id!)
  # @param _alias 
  # @param [Hash] opts the optional parameters
  # @return [ManagementPermissionReference]
  describe 'realm_identity_provider_instances_alias_management_permissions_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_management_permissions_put
  # Return object stating whether client Authorization permissions have been initialized or not and a reference
  # @param realm realm name (not id!)
  # @param _alias 
  # @param management_permission_reference 
  # @param [Hash] opts the optional parameters
  # @return [ManagementPermissionReference]
  describe 'realm_identity_provider_instances_alias_management_permissions_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_mapper_types_get
  # Get mapper types for identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_mapper_types_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_mappers_get
  # Get mappers for identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param [Hash] opts the optional parameters
  # @return [Array<IdentityProviderMapperRepresentation>]
  describe 'realm_identity_provider_instances_alias_mappers_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_mappers_id_delete
  # Delete a mapper for the identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param id Mapper id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_mappers_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_mappers_id_get
  # Get mapper by id for the identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param id Mapper id
  # @param [Hash] opts the optional parameters
  # @return [IdentityProviderMapperRepresentation]
  describe 'realm_identity_provider_instances_alias_mappers_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_mappers_id_put
  # Update a mapper for the identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param id Mapper id
  # @param identity_provider_mapper_representation 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_mappers_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_mappers_post
  # Add a mapper to identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param identity_provider_mapper_representation 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_mappers_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_alias_put
  # Update the identity provider
  # @param realm realm name (not id!)
  # @param _alias 
  # @param identity_provider_representation 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_alias_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_get
  # Get identity providers
  # @param realm realm name (not id!)
  # @param [Hash] opts the optional parameters
  # @return [Array<IdentityProviderRepresentation>]
  describe 'realm_identity_provider_instances_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_instances_post
  # Create a new identity provider
  # @param realm realm name (not id!)
  # @param identity_provider_representation JSON body
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_instances_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for realm_identity_provider_providers_provider_id_get
  # Get identity providers
  # @param realm realm name (not id!)
  # @param provider_id Provider id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'realm_identity_provider_providers_provider_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
