=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for KeycloakRest::KeyApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeyApi' do
  before do
    # run before each test
    @api_instance = KeycloakRest::KeyApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyApi' do
    it 'should create an instance of KeyApi' do
      expect(@api_instance).to be_instance_of(KeycloakRest::KeyApi)
    end
  end

  # unit tests for realm_keys_get
  # @param realm realm name (not id!)
  # @param [Hash] opts the optional parameters
  # @return [KeysMetadataRepresentation]
  describe 'realm_keys_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
