=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeycloakRest::MappingsRepresentation
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MappingsRepresentation' do
  before do
    # run before each test
    @instance = KeycloakRest::MappingsRepresentation.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MappingsRepresentation' do
    it 'should create an instance of MappingsRepresentation' do
      expect(@instance).to be_instance_of(KeycloakRest::MappingsRepresentation)
    end
  end
  describe 'test attribute "client_mappings"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "realm_mappings"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
