=begin
#Keycloak Admin REST API

#This is a REST API reference for the Keycloak Admin

The version of the OpenAPI document: 1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for KeycloakRest::MultivaluedHashMap
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MultivaluedHashMap' do
  before do
    # run before each test
    @instance = KeycloakRest::MultivaluedHashMap.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MultivaluedHashMap' do
    it 'should create an instance of MultivaluedHashMap' do
      expect(@instance).to be_instance_of(KeycloakRest::MultivaluedHashMap)
    end
  end
  describe 'test attribute "empty"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "load_factor"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "threshold"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
